# Generated by Django 5.2.8 on 2025-12-06 01:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('morning', 'Morning (8:00 AM)'), ('afternoon', 'Afternoon (2:00 PM)'), ('evening', 'Evening (8:00 PM)')], max_length=20)),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.PositiveIntegerField(help_text='Top number (e.g. 120)')),
                ('diastolic', models.PositiveIntegerField(help_text='Bottom number (e.g. 80)')),
                ('symptoms', models.TextField(blank=True, help_text='How you feel: headache, dizziness, etc.')),
                ('risk_level', models.CharField(choices=[('normal', 'Normal'), ('elevated', 'Elevated'), ('high', 'High (Stage 1/2)'), ('crisis', 'Hypertensive Crisis')], default='normal', max_length=20)),
                ('ai_advice', models.TextField(blank=True, help_text='Real advice from AWS Bedrock AI')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(blank=True, max_length=50)),
                ('frequency', models.CharField(choices=[('once', 'Once daily'), ('twice', 'Twice daily'), ('thrice', 'Three times daily')], default='once', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
                ('times', models.ManyToManyField(blank=True, to='core.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_times', to='core.medication')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, help_text='Your age (for better AI advice)', null=True)),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Name of person to contact in emergency', max_length=100)),
                ('emergency_contact_email', models.EmailField(blank=True, help_text='Email to alert in crisis', max_length=254)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
