# Generated by Django 5.2.8 on 2025-12-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthtip',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='healthtip',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='healthtip',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
